# render.yaml — Infrastructure as Code for Render
services:
  - type: web
    name: devops_ML-Project
    env: docker
    rootDir: phase2-docker-api
    dockerfilePath: ./Dockerfile
    branch: main
    autoDeploy: true   # Deploy automatically on every push!
    healthCheckPath: /health